spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ccm_mobile
    password: ccm_mobile
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    database: oracle
    show-sql: true