spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: motorcycle
    password: motorcycle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true