--------------------------------------------------------
--  Example data for Table USERS
--------------------------------------------------------

Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'admin','$2a$10$vAGoYGZS9AUtJBvIR8lpCuTEI3jk0XmT4WCN/LM3kEwaNqfTyWFMi','Admin','Admin','admin@admin','1');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'user','$2a$10$QbPycEIQ9J6D4mSmKws4L.sdYaCf7q10RwcUm9FX2Zbn7TDx.q.F.','User','User','user@user','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'donald','$2a$10$nYq.LtKlaU9Y00vnIyZA4OBmrr6YLuUkv59/HTgFlZcWEHhjKf9De','Donald','Trump','user2@user','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'barack','$2a$10$dIF6UuwPEuZmNnXbfbnNweE3/0gCILUYBtnD2a.JEUyRpwD1F1Aum','Barack','Obama','user3@user','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'bill','$2a$10$kchq0cuPfl60VsPXGy7DnOt.ybf1Ee2wNz7P95jTDd8uUw1rk9i3i','Bill','Clinton','user4@user','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'ronald','$2a$10$RTOMX3ziqQOme8sZtoyFlOupO/gYA.aTJW4.epsWKpBzdmOOLsMU6','Ronald','Reagan','ronald@reagan','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'jimmy','$2a$10$ppj1jtvzzaRI3td/pCLaleScaKV5HYK7dZYkpl1dWSSqFCm1jxp0S','Jimmy','Carter','jimmy@carter','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'gerald','$2a$10$mC0OdDqo/CjIF8210G06x.X7m5LTrlQcdq93JDKtQxU4aHwZ2ZAii','Gerald','Ford','gerald@ford','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'richard','$2a$10$dcHTybubIlqjNqy8QpIO/eihAhPANnXSl..WOFSQ8YpE5uYexBAOK','Richard','Nixon','admin2@admin','1');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'lyndon','$2a$10$o.68CybCCk.L23E8FMdQk.ExfAJurOcW/1MGSaZlBI2b3YpDSDbvS','Lyndon','Johnson','admin3@admin','1');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'john','$2a$10$xRMlCGq1GdZEpf2mocEX7.cTTakNJCrn6eyDosulsXT1FwWeSPPfO','John','Kennedy','john@kennedy','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'dwight','$2a$10$KNAt0nDT3AkLFgXSyi2vgulSTinWFq.2nANIRtsA2MrWRb.j0QHLe','Dwight','Eisenhower','dwight@eisenhower','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'harry','$2a$10$4B4/7HEQ58V6uPDEHUyR/.ity9EOJ8G3US5BZULmoKGh84CC5MZiq','Harry','Truman','harry@truman','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'herbert','$2a$10$LyaQxLpeGG2JrmSM2ILXr.BoJR2ZFuxxfJD5.1oM2lj0u0DiDv5xa','Herbert','Hover','herbert@hoover','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'calvin','$2a$10$DWs63MxUoxafRPJYCkkGD.sTnrPwzr/uG9LBT1WR8i5SZ0m/bdEfi','Calvin','Coolidge','calvin@coolidge','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'woodrow','$2a$10$9hb64FI8/Bs4ExLd0p0.H.5MkQgf7pBiUUY7NmS0yIOcKiLeg8RVC','Woodrow','Wilson','woodrow@wilson','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'theodore','$2a$10$FdkR2.Kg1A6EMS1gwq74TeJtcOFX3KuJKjLAdKipleyTF0FkQ9ZeO','Theodore','Roosevelt','theodore@roosevelt','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'ulysses','$2a$10$TfThef5vMSdk7NDDnmVgs.tK4QWAiZdu1hkG3Sju83SJ6DIwL9D0y','Ulysses','Grant','ulysses@grant','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'andres','$2a$10$QkQ8GSFqxAWEA.CSaHz5z.Wu4sh.TDtT1C4g222Gu.Ds3Eii6eku6','Andrew','Johnson','andrew@johnson','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'abraham','$2a$10$OWtwaFyEetPdStUgu9pqAuyogrhFOZXECvULqCJWBHNVN6cwOBrJa','Abraham','Lincoln','abraham@lincoln','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'jammes','$2a$10$AGxC3VFbGXDkW0lt4Y5UKOWlNydxGwHJ/16DQv6SZ1m3KExhiMA.O','James','Buchanan','james@buchanan','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'john','$2a$10$EuBhL7Y/R1Xd8xD8e14UKOWmZckJ7ZRtbHscUyFH8OLbVcSkyh0Ni','John','Tyler','john@tyler','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'martin','$2a$10$di27BCTe32ktMaiZznXP2uEyqtVdiDp.2Ee4nJMvRCQXKgbzY4ctC','Martin Van','Buren','martin@vanburen','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'thomas','$2a$10$aOOEROz4julOfBzdnt9jUOqYSHrGGlYORxxkI4WJIIVCGEAgXcDvG','Thomas','Jefferson','thomas@jefferson','0');
Insert into CCM_MOBILE.USERS (USR_ID,USR_LOGIN,USR_PASSWORD,USR_FIRST_NAME,USR_LAST_NAME,USR_EMAIL,USR_ADMIN) values (SEQ_USR_ID.nextval,'george','$2a$10$f2CB8PEQMthd0G4oR52pCe7DUJX5bGkl06osQM6b3MfRS027Ag68S','George','Washington','george@washington','1');
COMMIT;