--------------------------------------------------------
--  Example data for Table MOTORCYCLES
--------------------------------------------------------

INSERT INTO MOTORCYCLES (MTO_ID,MTO_MANUFACTURER,MTO_MODEL,MTO_PRODUCTION_YEAR,MTO_CAPACITY,MTO_POWER,MTO_WEIGHT,MTO_CONSUMPTION,MTO_TOP_SPEED,MTO_COLOUR,MTO_PRICE)
VALUES (SEQ_MTO_ID.NEXTVAL,'Ducati','P120',2016,1658,120,230,6.5,270,'Red',120);
COMMIT;